package com.github.rodrigotimoteo.animally.domain.export.pdf

internal fun headerBandOps(generatedAt: String): List<PdfOp> =
    listOf(
        PdfOp.Rect(
            x = PdfTheme.MARGIN,
            y = PdfTheme.MARGIN,
            width = PdfTheme.CONTENT_WIDTH,
            height = PdfTheme.HEADER_BAND_HEIGHT,
            color = PdfTheme.COLOR_BRAND,
        ),
        PdfOp.Text(
            "Animally",
            PdfTheme.MARGIN + PdfTheme.BAND_PAD_H,
            PdfTheme.MARGIN + PdfTheme.BRAND_TEXT_OFFSET_Y,
            PdfTheme.BRAND_SIZE,
            true,
            PdfTheme.COLOR_WHITE,
        ),
        PdfOp.Text(
            "Patient History Report",
            PdfTheme.MARGIN + PdfTheme.BAND_PAD_H,
            PdfTheme.MARGIN + PdfTheme.BAND_TITLE_OFFSET_Y,
            PdfTheme.BAND_TITLE_SIZE,
            false,
            PdfTheme.COLOR_WHITE,
        ),
        PdfOp.Text(
            generatedAt,
            PdfTheme.MARGIN + PdfTheme.CONTENT_WIDTH - PdfTheme.BAND_PAD_H,
            PdfTheme.MARGIN + PdfTheme.BAND_DATE_OFFSET_Y,
            PdfTheme.BAND_DATE_SIZE,
            false,
            PdfTheme.COLOR_WHITE,
            rightAligned = true,
        ),
    )

internal fun footerOps(
    pageNumber: Int,
    totalPages: Int,
    generatedAt: String,
): List<PdfOp> =
    listOf(
        PdfOp.Text(
            "Page $pageNumber of $totalPages",
            PdfTheme.PAGE_WIDTH / 2,
            PdfTheme.FOOTER_PAGE_LINE_Y,
            PdfTheme.FOOTER_SIZE,
            false,
            PdfTheme.COLOR_FOOTER,
            centered = true,
        ),
        PdfOp.Text(
            "Generated by Animally • $generatedAt",
            PdfTheme.PAGE_WIDTH / 2,
            PdfTheme.FOOTER_STAMP_LINE_Y,
            PdfTheme.FOOTER_SIZE,
            false,
            PdfTheme.COLOR_FOOTER,
            centered = true,
        ),
    )
