package com.github.rodrigotimoteo.animally.domain.export.pdf

/**
 * A single drawing instruction of the platform-neutral PDF layout model.
 *
 * Rectangles use a top-left origin; text [PdfOp.Text.y] is the top of the
 * text box. Platform painters translate these to their native APIs.
 */
internal sealed interface PdfOp {
    /**
     * Fills a rectangle.
     *
     * @property color ARGB fill color from [PdfTheme].
     */
    data class Rect(
        val x: Double,
        val y: Double,
        val width: Double,
        val height: Double,
        val color: Long,
    ) : PdfOp

    /**
     * Draws one line of text.
     *
     * @property y top edge of the text box.
     * @property rightAligned when set, [x] is the right edge.
     * @property centered when set, [x] is the center.
     */
    data class Text(
        val text: String,
        val x: Double,
        val y: Double,
        val size: Double,
        val bold: Boolean,
        val color: Long,
        val rightAligned: Boolean = false,
        val centered: Boolean = false,
    ) : PdfOp
}

/** One laid-out page of the report, with its footer metadata resolved. */
internal data class PdfPageModel(
    val pageNumber: Int,
    val totalPages: Int,
    val ops: List<PdfOp>,
)

/**
 * Builds the full page models for [report]: branded header band on every
 * page, demographics grid, one aligned table per non-empty section, and a
 * "Page X of Y" footer. Both platform renderers paint these ops verbatim,
 * which keeps the documents visually identical.
 */
internal fun layoutReport(report: PdfReportData): List<PdfPageModel> {
    val generatedAt = generationStamp()
    val contentOps = paginate(report)
    val totalPages = contentOps.size
    return contentOps.mapIndexed { index, ops ->
        val pageOps =
            buildList {
                addAll(headerBandOps(generatedAt))
                addAll(ops)
                addAll(footerOps(index + 1, totalPages, generatedAt))
            }
        PdfPageModel(
            pageNumber = index + 1,
            totalPages = totalPages,
            ops = pageOps,
        )
    }
}

// -------------------------------------------------------------------------
// Header band + footer
// -------------------------------------------------------------------------

private fun headerBandOps(generatedAt: String): List<PdfOp> =
    listOf(
        PdfOp.Rect(
            x = PdfTheme.MARGIN,
            y = PdfTheme.MARGIN,
            width = PdfTheme.CONTENT_WIDTH,
            height = PdfTheme.HEADER_BAND_HEIGHT,
            color = PdfTheme.COLOR_BRAND,
        ),
        PdfOp.Text(
            "Animally",
            PdfTheme.MARGIN + PdfTheme.BAND_PAD_H,
            PdfTheme.MARGIN + PdfTheme.BRAND_TEXT_OFFSET_Y,
            PdfTheme.BRAND_SIZE,
            true,
            PdfTheme.COLOR_WHITE,
        ),
        PdfOp.Text(
            "Patient History Report",
            PdfTheme.MARGIN + PdfTheme.BAND_PAD_H,
            PdfTheme.MARGIN + PdfTheme.BAND_TITLE_OFFSET_Y,
            PdfTheme.BAND_TITLE_SIZE,
            false,
            PdfTheme.COLOR_WHITE,
        ),
        PdfOp.Text(
            generatedAt,
            PdfTheme.MARGIN + PdfTheme.CONTENT_WIDTH - PdfTheme.BAND_PAD_H,
            PdfTheme.MARGIN + PdfTheme.BAND_DATE_OFFSET_Y,
            PdfTheme.BAND_DATE_SIZE,
            false,
            PdfTheme.COLOR_WHITE,
            rightAligned = true,
        ),
    )

private fun footerOps(
    pageNumber: Int,
    totalPages: Int,
    generatedAt: String,
): List<PdfOp> =
    listOf(
        PdfOp.Text(
            "Page $pageNumber of $totalPages",
            PdfTheme.PAGE_WIDTH / 2,
            PdfTheme.FOOTER_PAGE_LINE_Y,
            PdfTheme.FOOTER_SIZE,
            false,
            PdfTheme.COLOR_FOOTER,
            centered = true,
        ),
        PdfOp.Text(
            "Generated by Animally • $generatedAt",
            PdfTheme.PAGE_WIDTH / 2,
            PdfTheme.FOOTER_STAMP_LINE_Y,
            PdfTheme.FOOTER_SIZE,
            false,
            PdfTheme.COLOR_FOOTER,
            centered = true,
        ),
    )

// -------------------------------------------------------------------------
// Content pagination
// -------------------------------------------------------------------------

/** One atomic line of the demographics grid. */
internal data class KeyValueLine(
    val label: String,
    val value: String,
)

/** A section table prepared for drawing: widths, alignment and ellipsized cells resolved. */
internal class TableBlock(
    val title: String,
    val headers: List<String>,
    val widths: List<Double>,
    val alignRight: List<Boolean>,
    val bodyRows: List<List<String>>,
) {
    /** Draws one row of cells at [y] using the table's column geometry. */
    fun textOps(
        cells: List<String>,
        y: Double,
        bold: Boolean,
        color: Long,
    ): List<PdfOp> =
        cells.mapIndexed { index, cell ->
            val cellX = PdfTheme.MARGIN + widths.take(index).sum()
            val rightAligned = alignRight.getOrElse(index) { false }
            val textX = if (rightAligned) cellX + widths[index] - PdfTheme.CELL_PAD_H else cellX + PdfTheme.CELL_PAD_H
            PdfOp.Text(
                cell,
                textX,
                y + PdfTheme.CELL_TEXT_OFFSET_Y,
                PdfTheme.CELL_SIZE,
                bold,
                color,
                rightAligned = rightAligned,
            )
        }
}

private fun paginate(report: PdfReportData): List<List<PdfOp>> {
    val pages = mutableListOf<MutableList<PdfOp>>()
    var ops = newContentPage(pages)
    var y = PdfTheme.CONTENT_TOP

    for (line in demographicsLines(report)) {
        if (y + PdfTheme.DEMOGRAPHICS_LINE_HEIGHT > PdfTheme.CONTENT_BOTTOM) {
            ops = newContentPage(pages)
            y = PdfTheme.CONTENT_TOP
        }
        ops += keyValueOps(line, y)
        y += PdfTheme.DEMOGRAPHICS_LINE_HEIGHT
    }

    val tables = report.sections.filter { it.rows.size > 1 }.map(::buildTableBlock)
    if (tables.isEmpty()) {
        ops += emptyNoticeOp(y)
        return pages
    }

    for (table in tables) {
        y = drawTable(table, pages, y)
    }
    return pages
}

private fun newContentPage(pages: MutableList<MutableList<PdfOp>>): MutableList<PdfOp> {
    val ops = mutableListOf<PdfOp>()
    pages += ops
    return ops
}

private fun keyValueOps(
    line: KeyValueLine,
    y: Double,
): List<PdfOp> =
    listOf(
        PdfOp.Text(
            line.label,
            PdfTheme.MARGIN + PdfTheme.DEMO_LABEL_RIGHT_EDGE_OFFSET,
            y,
            PdfTheme.DEMOGRAPHICS_SIZE,
            true,
            PdfTheme.COLOR_LABEL,
            rightAligned = true,
        ),
        PdfOp.Text(
            line.value,
            PdfTheme.MARGIN + PdfTheme.DEMO_VALUE_X_OFFSET,
            y,
            PdfTheme.DEMOGRAPHICS_SIZE,
            false,
            PdfTheme.COLOR_TEXT,
        ),
    )

private fun emptyNoticeOp(y: Double): PdfOp =
    PdfOp.Text(
        "No records in range",
        PdfTheme.PAGE_WIDTH / 2,
        y + PdfTheme.EMPTY_NOTICE_OFFSET_Y,
        PdfTheme.SECTION_TITLE_SIZE,
        false,
        PdfTheme.COLOR_MUTED,
        centered = true,
    )

/**
 * Draws [table] starting at [y], splitting across pages at row boundaries.
 * The header row is never orphaned: when it would not fit together with at
 * least one body row, the whole table moves to the next page. Continuation
 * pages repeat the section title and header row. Returns the new y cursor.
 */
private fun drawTable(
    table: TableBlock,
    pages: MutableList<MutableList<PdfOp>>,
    startY: Double,
): Double {
    var ops = pages.last()
    var y = startY
    val tableHeaderHeight = PdfTheme.SECTION_TITLE_HEIGHT + PdfTheme.TITLE_TO_TABLE_GAP + PdfTheme.HEADER_ROW_HEIGHT

    fun ensureRoomForHeaderWithFirstRow() {
        if (y + tableHeaderHeight + PdfTheme.ROW_HEIGHT > PdfTheme.CONTENT_BOTTOM) {
            ops = newContentPage(pages)
            y = PdfTheme.CONTENT_TOP
        }
    }

    ensureRoomForHeaderWithFirstRow()
    ops += tableHeadOps(table, y)
    y += tableHeaderHeight

    table.bodyRows.forEachIndexed { index, row ->
        if (y + PdfTheme.ROW_HEIGHT > PdfTheme.CONTENT_BOTTOM) {
            ops = newContentPage(pages)
            y = PdfTheme.CONTENT_TOP
            ops += tableHeadOps(table, y)
            y += tableHeaderHeight
        }
        ops += bodyRowOps(table, row, y, zebra = index % 2 == 1)
        y += PdfTheme.ROW_HEIGHT
    }
    return y + PdfTheme.SECTION_GAP
}

private fun tableHeadOps(
    table: TableBlock,
    y: Double,
): List<PdfOp> =
    buildList {
        add(
            PdfOp.Text(table.title, PdfTheme.MARGIN, y, PdfTheme.SECTION_TITLE_SIZE, true, PdfTheme.COLOR_TEXT),
        )
        val headerY = y + PdfTheme.SECTION_TITLE_HEIGHT + PdfTheme.TITLE_TO_TABLE_GAP
        add(
            PdfOp.Rect(
                PdfTheme.MARGIN,
                headerY,
                PdfTheme.CONTENT_WIDTH,
                PdfTheme.HEADER_ROW_HEIGHT,
                PdfTheme.COLOR_BRAND,
            ),
        )
        addAll(table.textOps(table.headers, headerY, bold = true, color = PdfTheme.COLOR_WHITE))
    }

private fun bodyRowOps(
    table: TableBlock,
    row: List<String>,
    y: Double,
    zebra: Boolean,
): List<PdfOp> =
    buildList {
        if (zebra) {
            add(
                PdfOp.Rect(PdfTheme.MARGIN, y, PdfTheme.CONTENT_WIDTH, PdfTheme.ROW_HEIGHT, PdfTheme.COLOR_ROW_ALT),
            )
        }
        add(
            PdfOp.Rect(
                PdfTheme.MARGIN,
                y + PdfTheme.ROW_HEIGHT - PdfTheme.SEPARATOR_THICKNESS,
                PdfTheme.CONTENT_WIDTH,
                PdfTheme.SEPARATOR_THICKNESS,
                PdfTheme.COLOR_SEPARATOR,
            ),
        )
        addAll(table.textOps(row, y, bold = false, color = PdfTheme.COLOR_TEXT))
    }
